### PR TITLE
[TOREVIEW] Labo Java IO | Jeremie Melly

### LINKED ISSUE #1: Fix Unit Tests
Some of the units tests are not passing...

Working on it

### PR DESCRIPTION
**Pull request by jbstand**
Close #1

### CODE REVIEW

**Comment by jbstand** [comment]
So the DFSFileExplorerTest throws this :
image

But locally I've got this : 
image

Which is weird....

**Comment by jbstand** [comment]
And the ApplicationTest throws :
image

But locally I have : 
image
compared to 
image

Which are the same...

**Comment by jbstand** [comment]
The big question is :
Are the unit test of the github CI reliable?

**Comment by jbstand** [comment]
Waiting for approval to merge! 👍

**Comment by jbstand** [comment]
Forgot to add the TOREVIEW tag to the PR

**Review by jehrensb — APPROVED** [review]
Everything looks OK! Nice work.

Won't merge students' PRs, just approve.

**Pull request closed without merging**
